version: "3.5"

networks:
  buscalibre:
    #name: buscalibre
    driver: bridge
    ipam:
      config:
        - subnet: 172.21.0.0/24

services:
  DB:
    image: "postgres"
    container_name: "postgres"
    env_file:
      - "config.env"
    ports:
      - 5432:5432
    networks:
      buscalibre:
        ipv4_address: 172.21.0.2
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
  API:
    image: api
    container_name: "api"
    build: "./API"
    ports:
      - 80:5000
    networks:
      buscalibre:
        ipv4_address: 172.21.0.3
    env_file:
      - "config.env"
    depends_on:
      - DB
  BOT:
    image: bot
    container_name: "bot"
    build: "./BotTelegram"
    networks:
      buscalibre:
        ipv4_address: 172.21.0.4
    volumes:
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - "config.env"
    depends_on:
      - API
  SCRAPING:
    image: scraping
    container_name: scraping
    build: "./Scraping"
    networks:
      buscalibre:
        ipv4_address: 172.21.0.5
    volumes:
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - "config.env"
    depends_on:
      - DB